Outline implementation of quote providers
cmf-team/pricer pull request #22
Opened 2022-10-09 08:41 UTC by MikhailBespalov

The current version of code contains 3 various versions of classes, which download the price history for MOEX stocks

Currently several variants of realization could help to test the accuracy of downloaded prices for various intervals (ideally, the results should match)

After rewriting the code so the input and output elements would correspond to the design and testing the classed more thoughrouly, the most efficient and reliable will be left, while others may be used as supporting classes to perform testing.

The primary method in each class is getQuotes, which should return Interator with prices only (dates are already known and act as inputs)

2022-10-11 09:20 UTC, leonid-konovalov requested changes

2022-10-15 15:39 UTC, closed without merging

2022-10-15 23:57 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +# installation through terminal — pip install apimoex
ок

2022-10-15 23:57 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProviderTest.py
> +samplePrices = sampleQuoteObj.getQuotes('GAZP', sampleDates)
заменил, результат можно увидеть в тесте

2022-10-15 23:58 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +    ): self.__boardId = boardId
ок

2022-10-16 00:02 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +        self.__ticker = ticker
у меня ограниченный (и давний опыт) написания кода с помощью ООП. в теории я понимаю зачем это нужно, но отсутствие практике сказывается. в новой версии исправил, убрав большую часть self

2022-10-16 00:06 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +    def getChart(
done. QuoteInstpector принимает List из тикеров и две даты, после чего строит графики, volume из графиков убрал. QuoteInstpector ни от кого не наследуется, но при создании объекта в него нужно передавать boardId для последующей передачи в объект MoexQuoteProvider. можете объяснить разницу между пустыми и закрашанными стрелками на схеме? 
![image](https://user-images.githubusercontent.com/114314082/196011930-f0d17c10-db10-41d6-a77e-911a14217ad3.png)

2022-10-16 00:07 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProviderTest.py
> +sampleQuoteObj.getChart('SBER',date(2022,1,1),date(2022,10,10))
поправил