add IndexDiscountCurveTest, DiscountCurveTest classes and tests
cmf-team/pricer pull request #25
Opened 2022-10-11 21:12 UTC by igorlaryush

2022-10-14 13:24 UTC, leonid-konovalov requested changes

2022-10-14 13:24 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurve.py
> +    def tenorsToAct(self, durations) -> List:
Лучше __getDuration(tenor: str) -> float

2022-10-14 13:24 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurve.py
> +    def get_valuationDate(self) -> date:
Названия методов должны быть в lowerCamelCase.

2022-10-14 13:24 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurveTest.py
> +    def __init__(self, ticker_values: map):
Имена параметров должны быть в lowerCamelCase

2022-10-14 13:24 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurveTest.py
> +            tickers=["GAZP_1W"],
Тикеры лучше вида RATE1Y, причем тут Газпром непонятно.

2022-10-14 13:24 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurve.py
> +    @abc.abstractmethod
Нужно поменять @abc.abstractmethod на @abstractmethod чтобы было одинаково по всему проекту.

2022-10-14 13:24 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurve.py
> +        """Get discont factor for a certain date"""
Пропущен параметр paymentDate. Не хватает pass. Документацию, не добавляющую новой информации делать не нужно.

2022-10-14 13:24 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurve.py
> +        """Get valuation date"""
Не хватает pass. Документацию, не добавляющую новой информации делать не нужно.

2022-10-14 13:24 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurveTest.py
> +class VanillaStructuredProductTest(TestCase):
Лучше сделать одну кривую в методе setUp, участвовать должны теноры со всеми возможными буквами. Для нее уже в отдельных тестировать значения в точках, соответствующих тенорам, интерполяцию и экстраполяцию.

2022-10-15 13:22 UTC, leonid-konovalov requested changes

2022-10-15 13:22 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurve.py
> +class DiscountCurve(ABC):
В большинстве случаев каждый класс должен быть в отдельном модуле:
![image](https://user-images.githubusercontent.com/74711923/195988453-0bca36bf-41a4-41f9-a5a1-e6785fec1001.png)

2022-10-15 13:22 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurve.py
> +    def get_valuationDate(self) -> date:
Ошибка в названии метода
![image](https://user-images.githubusercontent.com/74711923/195988524-f6fc8fce-cbc0-499b-b0af-c1ccc8ace40f.png)

2022-10-15 13:22 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurve.py
> +        self.valuationDate = valuationDate
Видимость должна быть private
![image](https://user-images.githubusercontent.com/74711923/195988571-ab55121c-9bfd-4a91-91b3-6b806d23ea4b.png)

2022-10-15 13:22 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurve.py
> +            if duration[-1] == 'D':
Вместо duration[-1] == 'D' PEP8 предписывает использовать endswith.

2022-10-15 13:31 UTC, igorlaryush commented on Implementation/Products/IndexDiscountCurve.py
> +        self.valuationDate = valuationDate
А как тогда метод getValuationDate будет возвращать дату если она прайвет или ничего страшного так и должно быть?

2022-10-15 15:39 UTC, closed without merging

2022-10-15 16:53 UTC, leonid-konovalov commented on Implementation/Products/IndexDiscountCurve.py
> +        self.valuationDate = valuationDate
```
def getValuationDate() -> date:
    return self.__valuationDate
```