Расчет базовой цены продукта с защитой капитала
cmf-team/pricer pull request #27
Opened 2022-10-14 19:03 UTC by pacifikus

2022-10-14 19:04 UTC, pacifikus commented
В пункте "Для расчета ожидаемых значений в тестах можно использовать online-калькуляторы, например https://goodcalculators.com/black-scholes-calculator/." - местами не совпадают значения, возможно, я что-то упустила в расчетах...

2022-10-14 22:15 UTC, leonid-konovalov requested changes

2022-10-14 22:15 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricer.py
> +        S_t = self.__originalMarket.getQuotes(
В качестве имен переменных, кроме d1 и d2, нужно использовать термины - spotPrice, forwardPrice, strike, discountFactor, totalVariance.

2022-10-14 22:15 UTC, leonid-konovalov commented on requirements.txt
> +scipy==1.9.2
Повторяющаяся строка.

2022-10-14 22:15 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricerTest.py
> +    def testCallOptionBasePriceInTheMoneyPayoff(self):
1. Нужно сделать через subtest.
2. Тестируем цену, а в названии Payoff.

2022-10-14 22:15 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricerTest.py
> +class DiscountCurveStub(DiscountCurve):
Здесь лучше использовать Mock - возвращается один и тот же результат вне зависимости от входных параметров, нет необходимости усложнять код дополнительным классом.

2022-10-14 22:15 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricerTest.py
> +            self.__testedPricer.getDiscountFactor(date_), exp(-rate * 30 / 365)
Здесь лучше проверить равенство факторов дисконтирования, возвращаемых классом SimulationPricer и кривой.

2022-10-14 22:23 UTC, pacifikus commented on Implementation/Products/QuoteProvider.py
> +    def getQuotes(self, ticker: str, observationDates: List[date]) -> List[float]:
А сколько у нас в символах длина строки? У меня просто 88 стоит, поэтому стиль разный.
 
Еще, может быть, стоит добавить в github actions проверку стилей вместе с настроенными линтерами? например flake8? Или вообще [precommit-hook](https://pre-commit.com/), тогда на стороне разработчика нельзя было бы сделать коммит, не исправив стиль кода...

2022-10-14 22:29 UTC, leonid-konovalov commented on Implementation/Products/QuoteProvider.py
> +    def getQuotes(self, ticker: str, observationDates: List[date]) -> List[float]:
![image](https://user-images.githubusercontent.com/74711923/195952669-15f19854-6d1f-44da-8e53-a5a57a366bfd.png)

Линтер это было бы здорово, но думаю это очень трудоемко, масса настроек. Я смотрел pylint, он совсем не то делает по умолчанию.

Мне понравился autoformatter в PyCharm, он почти все по CodeGuidelines делает.

2022-10-14 22:35 UTC, pacifikus commented on Implementation/Products/QuoteProvider.py
> +    def getQuotes(self, ticker: str, observationDates: List[date]) -> List[float]:
Спасибо! Сделала у себя тоже 79.

Еще сейчас нашла в настройках PyCharm включение автоформатирования перед коммитом. Раз нам это подходит, может быть остальным тоже показать? 
![image](https://user-images.githubusercontent.com/22592039/195953500-421ff6f8-99c2-4639-aabc-a75660773c96.png)

2022-10-15 07:43 UTC, leonid-konovalov commented on Implementation/Products/QuoteProvider.py
> +    def getQuotes(self, ticker: str, observationDates: List[date]) -> List[float]:
Спасибо, расскажу об этом на звонке.

2022-10-15 12:24 UTC, pacifikus commented on Implementation/Simulation/SimulationPricer.py
> +        sigma_T = self.__covariance.getTotalCovariance(maturityDate)
Не совсем понятно, как из матрицы взять элемент, соответствующий underlying. Там будет какая-то индексация с наименованиями? Как в pandas датафреймах, например? В диаграмме сейчас отсутствует data type.

2022-10-15 12:45 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricer.py
> +        sigma_T = self.__covariance.getTotalCovariance(maturityDate)
Нужно добавить интерфейс Matrix с соответствующим абстрактным методом. Индексацию давайте сделаем как в numpy.
![image](https://user-images.githubusercontent.com/74711923/195987084-cded2e35-43f3-4528-9538-cc2b84108309.png)

Предполагается далее что это будет array из numpy, либо tensor из torch.

Индексация underlyings такая же, как в классе SimulationPricer.

2022-10-15 14:30 UTC, pacifikus commented on Implementation/Products/VanillaStructuredProduct.py
> +        return pricer.getCallOptionBasePrice(
Не совсем поняла, как учесть cap, можно где-то формулу посмотреть?

2022-10-15 16:48 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProduct.py
> +        return pricer.getCallOptionBasePrice(
Я думаю вы можете до нее догадаться, несложная задача.

2022-10-15 18:08 UTC, leonid-konovalov requested changes

2022-10-15 18:08 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricerTest.py
> +    @patch('Simulation.CovarianceTermStructure')
Параметр 'Simulation.CovarianceTermStructure' не меняется автоматически при рефакторинге. А так все будет меняться:
        mockСovariance = Mock(spec=CovarianceTermStructure)
        mockСovariance.getTotalCovariance = Mock(return_value=np.array([[0.01]]))

2022-10-15 18:08 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricerTest.py
> +    def getQuotes(
Здесь лучше Mock вместо Stub (чтобы не было дополнительного класса), тем более только одно значение возвращается.

2022-10-15 18:08 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProduct.py
> +        strike = self.__capStrike if self.__cap else self.__strike
На этот метод определенно нужен тест.

2022-10-15 19:23 UTC, pacifikus commented on Implementation/Products/VanillaStructuredProduct.py
> +        strike = self.__capStrike if self.__cap else self.__strike
Тесты нужны в виде `testCappedBasePrice`/`testUnCappedBasePrice`? В соседнем PR все сильно перекроилось, тогда после `merge` снова понадобится рефакторинг... Может быть, дождаться обновленных тестов для `VanillaStructuredProductTest `и сделать в отдельной ветке тест?

2022-10-15 19:44 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProduct.py
> +        strike = self.__capStrike if self.__cap else self.__strike
В соседней ветке тесты на метод getPaymentAmount, здесь тесты на getBasePrice.
Можно сделать merge другой ветки (в ее текущем состоянии) в эту, и добавить дополнительные тесты.

2022-10-17 18:55 UTC, leonid-konovalov requested changes

2022-10-17 18:55 UTC, leonid-konovalov commented on Implementation/Simulation/CovarianceTermStructure.py
> +    def getTotalCovariance(self, ForecastDate: date):
Имя параметра должно быть с маленькой буквы.

2022-10-17 18:55 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricer.py
> +    def __init__(
Базовый класс Pricer нужно сделать абстрактным.

2022-10-17 18:55 UTC, leonid-konovalov commented on Implementation/Products/Derivative.py
> +    pricer = None
Здесь должен быть не pricer, а pricerCreator.

2022-10-17 18:55 UTC, leonid-konovalov commented on Implementation/Products/Derivative.py
> +        Derivative.pricer = newPricerCreator.createPricer()
Вызов createPricer() будет осуществляться в методе getPrice.

2022-10-17 18:55 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricer.py
> +        totalCovariance = self.__covariance.getTotalCovariance(maturityDate)
Немного вводящее в заблуждение название переменной. Лучше обойтись без нее и сразу задать значение totalVariance.

2022-10-17 18:55 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricerTest.py
> +                    places=1
Здесь определенно точность должна быть выше. Сейчас есть явная ошибка в методе, вычисляющем цену.

2022-10-20 09:38 UTC, leonid-konovalov requested changes

2022-10-20 09:38 UTC, leonid-konovalov commented on Implementation/Products/PricerFactory.py
> +        marker: QuoteProvider
Ошибка в имени параметра.

2022-10-20 09:38 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProductTest.py
> +            "underlyingQuote expected"
Лучше через list чтобы проще читалось:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/74711923/196909749-80743e12-6951-4292-978e-798f770495fb.png">

2022-10-20 09:38 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProductTest.py
> +        expected = self.pricer.getCallOptionBasePrice(
expected - прилагательное, лучше expectedResult.

2022-10-20 16:28 UTC, leonid-konovalov requested changes

2022-10-20 16:28 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricer.py
> +        self.__covariance = covariance
В дизайне другое имя атрибута:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/74711923/197002398-a77b5152-a60e-41b1-9bf6-23d4cac24e32.png">

2022-10-20 16:28 UTC, leonid-konovalov commented on Implementation/Simulation/SimulationPricer.py
> +    def getValuationDate(self) -> date:
Метод не в том же порядке, что в дизайне.

2022-10-20 16:28 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProduct.py
> +            return callOptionBasePrice - callCapOptionBasePrice + 1
Здесь и ниже выплату номинала 1 нужно умножить на фактор дисконтирования.

2022-10-20 16:28 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProductTest.py
> +        return 300 - strike
Если можно, то для реалистичности лучше сделать max(300 - strike, 0). Так при чтении строки будет возникать меньше вопросов.

2022-10-20 16:28 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProductTest.py
> +            maturityDate=date(2022, 9, 1),
Лишняя запятая.

2022-10-20 16:28 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProductTest.py
> +            cap=0.08,
Лишняя запятая

2022-10-20 16:28 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProductTest.py
> +        self.pricer = PricerStub()
Видимость должна быть private, чтобы строка не привлекала внимание.

2022-10-20 16:28 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProductTest.py
> +                    ),
Лишняя запятая

2022-10-20 16:28 UTC, leonid-konovalov commented on Implementation/Simulation/DiscountCurve.py
> +    def getDiscountFactor(self, paymentDate) -> float:
Не указан тип параметра paymentDate.

2022-10-20 18:33 UTC, pacifikus commented on Implementation/Products/VanillaStructuredProduct.py
> +            return callOptionBasePrice - callCapOptionBasePrice + 1
Имеется в виду `pricer.getDiscountFactor(valuationDate)`?

2022-10-20 19:28 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProduct.py
> +            return callOptionBasePrice - callCapOptionBasePrice + 1
Да

2022-10-21 11:20 UTC, leonid-konovalov approved these changes
Сделайте, пожалуйста, описание merge commit такого плана, без упоминания имен веток, номеров issue или pull request:

![image](https://user-images.githubusercontent.com/74711923/197184329-959c305b-5afc-4ae3-a305-ad195ff7ab2f.png)

2022-10-21 11:20 UTC, leonid-konovalov commented on Implementation/Products/VanillaStructuredProductTest.py
> +                    ),
Лишняя запятая

2022-10-21 15:30 UTC, merged