4 реализовать загрузку котировок цен акций котирующихся на московской бирже
cmf-team/pricer pull request #29
Opened 2022-10-15 23:55 UTC by MikhailBespalov

Separate QuoteInspector created for visualization purposes

Other comments for the previous commit are also taken into account and the code is corrected in accordance with them

2022-10-18 08:51 UTC, leonid-konovalov requested changes

2022-10-18 08:51 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +            pricesList = mergedResult['CLOSE'].tolist()
Лишняя переменная pricesList, можно сразу вернуть mergedResult['CLOSE'].tolist()

2022-10-18 08:51 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +            quotesData = apimoex.get_board_history(
С помощью get_market_history можно обойтись без merge?

with requests.Session() as session:
    ticker = 'SNGSP'
    data = pandas.DataFrame(apimoex.get_market_history(session, ticker))
    data.set_index('TRADEDATE', inplace=True)

2022-10-18 08:51 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +    def getChartQuotes(
Этот метод пока представляет собой ненужную сложность. QuoteInspector должен использовать только метод getQuotes. Да, так не будет информации об объемах, но при этом можно будет использовать любой QuoteProvider, чем мы воспользуемся в частности для ставок.

2022-10-18 08:51 UTC, leonid-konovalov commented on Implementation/Markets/QuoteInspector.py
> +        for i in range(0, len(tickers)):
В теле цикла индекс используется только для получения тикера (tickers[i]).

Соответственно, лучше написать так:

for ticker in tickers:
...
chartDf = inspectedObject.getChartQuotes(
                ticker,
                startDate,
                endDate
            )

2022-10-18 08:51 UTC, leonid-konovalov commented on Implementation/Markets/QuoteInspector.py
> +    sampleChartObj = QuoteInspector('TQBR')
Переменные должны читаться: sampleChartObject, вместо sampleChartObj.

2022-10-18 08:51 UTC, leonid-konovalov commented on Implementation/Markets/QuoteInspector.py
> +    tickerList = ['GAZP', 'SBER', 'OZON']
Тип переменной не должен присутствовать в ее имени. Здесь можно sampleTickers.

2022-10-18 08:51 UTC, leonid-konovalov commented on requirements.txt
> +requests
Нужно указать версии библиотек

2022-10-18 08:51 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProviderTest.py
> +sampleQuoteObj = MoexQuoteProvider('TQBR')
Переменные должны читаться: sampleChartObject, вместо sampleChartObj.

2022-10-18 08:51 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +        startDate: date = min(observationDates)
Внутри функции типы переменных не прописываем, за исключением случаев, когда IDE не может их определить.

2022-10-18 08:51 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +    def __init__(
Декларация помещается в одной строке, в этом случае параметры размещать в отдельных строках не нужно.

2022-10-18 08:51 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProviderTest.py
> +for i in range(0, len(sampleDates)):
Вместо range(0, len(sampleDates)) можно писать range(len(sampleDates)).

2022-10-18 22:18 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +            quotesData = apimoex.get_board_history(
посмотрел метод get_market_history, существенных отличий в возвращаемых данных или параметров, которые позволили бы привести эти данные к требуемому виду (список из элементов типа float который привязан к набору входных дат) не нашел. манипуляции с merge, который в pandas в данном случае вытупает аналогом join в sql нужны только для того, чтобы смэтчить изначальные даты и полученные значения, а затем там, где дат нет - вписать None. вероятно можно сделать это другими способами, без pandas, но этот, на мой взляд, наиболее удобный

2022-10-18 23:43 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +    def getChartQuotes(
изначально, когда я высказывал мысль о том, что getQuotes должен возвращать именно DataFrame, а не List of floats, я в том числе думал о графиках и то как этот список придется потом обрабатывать. поскольку getQuotes возвращает только close, на его основе можно построить только обычный график - линию. информация о минимумах и максимумах, если она будет каким либо образом важна для оценки продуктов, теряется.
+ приходится сначала обрабатывать данные в классе MoexQuoteProvider, приводя их к нужному виду через merge, а потом в QuoteInspector снова собирать из них необходимый для графика DataFrame, вычищая None, что отрицательно сказывается на скорости. в любом случае - релизовал, графики теперь выглядят вот так
![image](https://user-images.githubusercontent.com/114314082/196565118-d1a5a8c9-79d9-47eb-9022-486bc6480e31.png)

2022-10-18 23:44 UTC, MikhailBespalov commented on Implementation/Markets/QuoteInspector.py
> +        for i in range(0, len(tickers)):
ок

2022-10-18 23:45 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +            pricesList = mergedResult['CLOSE'].tolist()
ок

2022-10-18 23:45 UTC, MikhailBespalov commented on Implementation/Markets/QuoteInspector.py
> +    sampleChartObj = QuoteInspector('TQBR')
ok

2022-10-18 23:51 UTC, MikhailBespalov commented on requirements.txt
> +requests
ок, указал последние версии, которые смог найти в сети

2022-10-18 23:51 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProviderTest.py
> +sampleQuoteObj = MoexQuoteProvider('TQBR')
ок

2022-10-18 23:55 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +        startDate: date = min(observationDates)
хорошо. здесь я прописал тип в том числе потому, что метод get_board_history из apimoex должен принимать даты в формате строки, но, как ни странно, правильно работает он только если на вход подаются именно даты, со стороками выдает ошибку

2022-10-18 23:58 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +    def __init__(
ок

2022-10-18 23:59 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProviderTest.py
> +for i in range(0, len(sampleDates)):
ок

2022-10-19 00:15 UTC, MikhailBespalov commented
есть следующие вопросы:

1) сейчас котировки возвращаются на конец предыдущего дня, но не на сегодняшний день, если торги уже начались. с какого именно момента apimoex считает, что день закончен - не совсем понятно, но, судя по тому, что котировки для TQBR возвращаются для вечерней сессии - это поздний вечер или уже следующий день. нужно ли дополнительно возращать котировки на текущую дату, если она присутствует в списке дат  (скажем, на момент закрытия предыдущего часа)? 

2) касательно проблемы с FinamQuoteProvider (поддержание в актуальном состоянии списка соответствия тикеров и finam id для формирования правильных ссылок) - я нашел для нее решение, но, на первый взгляд оно кажется достаточно громоздким. описано вот здесь: 

**selenium на Python за 25 минут: автоматизированная выгрузка FinAM 
https://www.youtube.com/watch?v=opLTLRyI-eI**

ко всему прочему несколько смущает вот это

![image](https://user-images.githubusercontent.com/114314082/196567899-8f988df0-c85e-4f5e-95af-fc47646b3eae.png)

нужно ли реализовывать FinexQuoteProvider и FinamQuoteProvider, если текущий класс обеспечивает необходимый функционал?

2022-10-19 10:05 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +        datesDf = pandas.DataFrame(observationDates)
Имя datesDf состоит из двух имен типов, таким образом ничего не говорит читателю о том, какова роль переменной.

В данном случае роль - "даты, котировки на которые мы отберем и вернем в качестве результата". Переменную можно назвать resultDates, например.

2022-10-19 10:06 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +            mergedResult = datesDf.merge(
Слово "merged" здесь немного вводит в заблуждение, в действительности происходит отбор котировок на дату. Переменную можно назвать просто result.

2022-10-19 10:08 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +            moexDf = pandas.DataFrame(quotesData)
Лишняя переменная moefDf, лучше сразу так сделать:

```
quotesData = pandas.DataFrame(
    apimoex.get_board_history(
        session,
        ticker,
        startDate,
        endDate,
        columns,
        self.__boardId
    )
)
```

2022-10-19 10:10 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +from Products.QuoteProvider import QuoteProvider
Imports не соответствуют PEP8

2022-10-19 10:16 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +        startDate: date = min(observationDates)
Напишите, пожалуйста, комментарий об этом перед вызовом метода.

![image](https://user-images.githubusercontent.com/74711923/196663944-9bae13cc-643e-459d-87b8-ac2809195efb.png)

2022-10-19 10:17 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +        startDate: date = min(observationDates)
Вы используете PyCharm?

2022-10-19 10:27 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProvider.py
> +    def getChartQuotes(
Желание добавить дополнительную информацию и провести оптимизацию понятно. Вопрос в том, что мы при этом получаем и что теряем.

Информация о минимумах и максимумах почти наверняка нам не потребуется, разница в производительности вряд ли наблюдаема. А вот если мы будем накладывать ограничение на QuoteProvider в виде использования pandas, то это будет существенной проблемой - на каком-то этапе потеряем возможность использовать автоматическое дифференцирование из torch, возможно векторизацию из NumPy. Это помимо того, что будем вынуждены формировать DataFrames там, где без этого можно будет обойтись.

2022-10-19 10:28 UTC, leonid-konovalov commented
`есть следующие вопросы:

сейчас котировки возвращаются на конец предыдущего дня, но не на сегодняшний день, если торги уже начались. с какого именно момента apimoex считает, что день закончен - не совсем понятно, но, судя по тому, что котировки для TQBR возвращаются для вечерней сессии - это поздний вечер или уже следующий день. нужно ли дополнительно возращать котировки на текущую дату, если она присутствует в списке дат (скажем, на момент закрытия предыдущего часа)?

касательно проблемы с FinamQuoteProvider (поддержание в актуальном состоянии списка соответствия тикеров и finam id для формирования правильных ссылок) - я нашел для нее решение, но, на первый взгляд оно кажется достаточно громоздким. описано вот здесь:

selenium на Python за 25 минут: автоматизированная выгрузка FinAM
https://www.youtube.com/watch?v=opLTLRyI-eI

ко всему прочему несколько смущает вот это

image

нужно ли реализовывать FinexQuoteProvider и FinamQuoteProvider, если текущий класс обеспечивает необходимый функционал?`

2022-10-20 20:53 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +        startDate: date = min(observationDates)
сейчас еще раз попробовал передавать строки типа ГГГГ-ММ-ДД, в pycharm всё работает нормально, когда на начальном этапе тестировал в Jupyter, то метод выдавал ошибку. вместо комментария исправил код. для внесения правок в код класса использую PyCharm, но в парралельном окне открыт Jupyter для тестов отдельных новых элементов кода, успел привыкнуть к нему - удобно, когда код разбит на разные части, которые можно отдельно запускать и править

2022-10-20 21:05 UTC, MikhailBespalov commented on Implementation/Markets/QuoteInspector.py
> +    def __init__(
для get_market_history и других методов apimoex проблема заключается в том, что методы возвращают только те даты, для которых есть данные, а праздники и выходные не возвращают. поэтому, если у нас во входных датах случайно попадется такой день, в который нет торгов, то фильтрация здесь не сработает => выходной список floats не будет соответствовать входным датам, а возвращаем мы только его. поэтому merge или другой аналог мэтчинга входных дат и цен в любом случае нужен
![image](https://user-images.githubusercontent.com/114314082/197057276-78f0c31e-c095-4ec3-b208-4673af57745a.png)

по декларации метода - ок

2022-10-20 21:16 UTC, MikhailBespalov commented on Implementation/Markets/QuoteInspector.py
> +import plotly.graph_objects
я так понимаю правильно вот так. исправил 
![image](https://user-images.githubusercontent.com/114314082/197059682-7a3879bb-0e9d-40c5-be43-ae1d6cc97ea6.png)

![image](https://user-images.githubusercontent.com/114314082/197059852-e90f2424-d032-4a61-9c08-1ba7194f3986.png)

2022-10-20 21:19 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +            quotesData = apimoex.get_board_history(
не знаю насколько это важно с точки зрения понимания кода, но ок, поправил

2022-10-20 21:23 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +        datesDf = pandas.DataFrame(observationDates)
ок

2022-10-20 21:24 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +            mergedResult = datesDf.merge(
ok

2022-10-20 21:26 UTC, leonid-konovalov commented on Implementation/Markets/QuoteInspector.py
> +        inspectedObject = MoexQuoteProvider(self.__boardId)
Не совсем. Я имел в виду следующее:
`def __init__(self, inspectedObject: QuoteProvider)`

2022-10-20 21:27 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +            moexDf = pandas.DataFrame(quotesData)
ок

2022-10-20 21:34 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +from Products.QuoteProvider import QuoteProvider
возможно, но в других классах, которые вы, кажется, писали еще во время первого звонка конструкция именно такая. в code guidlines аналогичная конструкция обозначена как верная. объясните, пожалуйста, как правильно

![image](https://user-images.githubusercontent.com/114314082/197062337-44677302-9c1e-4557-8979-aaafa560f2a2.png)

![image](https://user-images.githubusercontent.com/114314082/197062491-51debb29-1dbd-4d00-adad-299ce564feed.png)

![image](https://user-images.githubusercontent.com/114314082/197063153-fb8f6bd8-977f-4ed7-a9a6-50e076d9a21c.png)

2022-10-20 21:49 UTC, MikhailBespalov commented on Implementation/Markets/QuoteInspector.py
> +        inspectedObject = MoexQuoteProvider(self.__boardId)
т.е. мы при создании объекта QuoteInspector передаем ему не boardId, а объект класса QuoteProvider или классов, которые наследуют от QuoteProvider, так? 

я полагал, что слово create здесь подразумевает создание объекта разновидности QuoteProvider внутри самого класса QuoteInspector.


![image](https://user-images.githubusercontent.com/114314082/197065162-e2fc8ad4-42ca-48a2-84c1-e86b944ec679.png)

2022-10-20 21:54 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProvider.py
> +from Products.QuoteProvider import QuoteProvider
я так понимаю это вопрос группировки importов. не совсем понял, что здесь значит case-sensitive. те, у которых после from название написано с большой буквы должны идти в начале? 
![image](https://user-images.githubusercontent.com/114314082/197066304-bcdacf16-9789-4131-b3db-47082d9abefb.png)

2022-10-20 22:16 UTC, MikhailBespalov commented
C FinamQuoteProvider, а именно с автоматической выгрузкой списка соответствия TICKER => FINAM ID я могу разбираться долго. судя по видосу, который кидал выше, там всё не так тривиально. думаю лучше перейти к другим задачам, а к этой вернуться, если возникнет такая необходимсть. 

загружаю очередной коммит. в QuoteInspector теперь при создании объекта передается заранее созданный объект MoexQuoteProvider. надеюсь, правильно понял вашу мысль

2022-10-20 22:37 UTC, MikhailBespalov commented
к сожалению, обе попытки коммита не прошли. пишет, что не может найти тестовый модуль 
![image](https://user-images.githubusercontent.com/114314082/197072004-db57b70f-1b0b-495a-9031-425a7c39ad1f.png)

2022-10-21 10:55 UTC, leonid-konovalov commented
Давайте попробуем оформить тест с помощью библиотеки unittest. В качестве примера можно посмотреть VanillaStructuredProductTest.py.

2022-10-22 17:38 UTC, leonid-konovalov requested changes

2022-10-22 17:38 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProviderTest.py
> +    main()
Этот код не нужен.

2022-10-22 17:38 UTC, leonid-konovalov commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" project-jdk-name="Python 3.9" project-jdk-type="Python SDK" />
Мы используем Python 3.10, его нужно установить. Нужно откатить изменения в файлах misc.xml и pricer.iml.

2022-10-22 17:43 UTC, leonid-konovalov requested changes

2022-10-22 17:43 UTC, leonid-konovalov commented on Implementation/Markets/MoexQuoteProviderTest.py
> +        sampleDates = [date(2022, 1, 9), date(2022, 2, 10), date(2022, 10, 3),
Форматирование не соответствует PEP8 с точки зрения PyCharm:
![image](https://user-images.githubusercontent.com/74711923/197355110-10d8465d-636a-4654-8f7d-8932b2196c67.png)

Можно так, аналогично тому, как форматируем параметры методов, если декларация не входит в одну строку.

![image](https://user-images.githubusercontent.com/74711923/197355085-1608a4cf-d4cd-41a2-8cd4-7f95e3a6afae.png)

2022-10-22 18:50 UTC, MikhailBespalov commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" project-jdk-name="Python 3.9" project-jdk-type="Python SDK" />
3.10 сейчас устанавливаю через conda. судя по всему, это не быстрый процесс. судя по тому, что я вижу в истории, изменения в эти файлы были внесены автоматически еще 11 октября. нашел способ отменять изменения с помощью консоли (git checkout), но у меня этот способ не сработал. не подскажите, как сделать откат конкретно для этих двух файлов?

2022-10-22 18:52 UTC, MikhailBespalov commented on Implementation/Markets/MoexQuoteProviderTest.py
> +        sampleDates = [date(2022, 1, 9), date(2022, 2, 10), date(2022, 10, 3),
ок

2022-10-22 20:38 UTC, leonid-konovalov approved these changes
Сделайте, пожалуйста, описание merge коммита без упоминаний веток, номеров Issues и тому подобного. Не забудьте также про опцию --no-ff

2022-10-23 16:51 UTC, MikhailBespalov commented
![image](https://user-images.githubusercontent.com/114314082/197404724-f1431e0f-7d22-4ba0-b1b3-232c5d2859b7.png)
такое название формуруется автоматические, если сначала сделать resolve conflics руками и уже оттуда отправить коммит

сейчас сделал последний финальный коммит, убрав ненужные куски кода, которые заметил сегодня на звонке. я это  через git hub desktop, а не через консоль. там нет таких опций. насколько я понимаю, они про то, чтобы разные ветки не перепутались

![image](https://user-images.githubusercontent.com/114314082/197404896-12ffa944-13c8-4413-8102-9a428d0dbd6d.png)

после последнего коммита с кодом вроде всё должно быть нормально. можно сделать мердж отсюда?

2022-10-23 18:13 UTC, leonid-konovalov commented
В таком случае Вы можете сделать merge локально через командную строку git, а затем push.

2022-10-23 19:24 UTC, MikhailBespalov commented
> В таком случае Вы можете сделать merge локально через командную строку git, а затем push.

Если локально - мы же конкретную в ветку в мастер хоим замерджить. Я не совсем понимаю в таком случае как это сделаеть без ее упоминания 
![image](https://user-images.githubusercontent.com/114314082/197411987-c6860cc2-98c9-4488-a857-356061457f77.png)

2022-10-23 19:58 UTC, leonid-konovalov commented
После этого до push поменять сообщение можно с помощью
git commit --amend

2022-10-24 20:56 UTC, merged

2022-10-24 21:00 UTC, MikhailBespalov commented
> После этого до push поменять сообщение можно с помощью git commit --amend

![image](https://user-images.githubusercontent.com/114314082/197626884-f3b6d6eb-f59c-4077-b9e9-44212ca292cf.png)
спасибо, так сделал. после этого сделал git push